### ISSUE TITLE
SERIES THAT DON'T LOAD

### ISSUE THREAD

**Issue by jarvis710** [jhassan8/crunchyroll-tizen#100]
SOME OF THE SERIES BLOCK THE APP. THEY ONLY SHOW THE INITIAL SCREEN OF THE SERIES, IF YOU ENTER EPISODES, IT DOES NOT SHOW INFORMATION; AND IF YOU TRY TO PLAY THE EPISODE FROM THE HOME SCREEN OF THE SERIES, GO TO THE PLAYER AND THERE THE APP CRASHES.

**Comment by jhassan8** [comment]
Hi @jarvis710, do you have an example of what series, episodes and the audio and subtitle settings you have... to be able to replicate the error

**Comment by jarvis710** [comment]
The audio and subtitle settings, I usually leave the audio in Japanese and subtitles in Spanish or put in English audio without subtitles. The series that generate this crash are of the mature or similar category. Example: High School DXD, Prison School, Ikki Tousen, Freezing

**Comment by jhassan8** [comment]
hi @jarvis710, the official application is now available in the TV store. regards

**Comment by jarvis710** [comment]
Thanks
