### ISSUE TITLE
Will this app be continued?

### ISSUE THREAD

**Issue by Rukko** [jhassan8/crunchyroll-tizen#102]
https://www.crunchyroll.com/news/announcements/2024/2/5/crunchyroll-app-now-available-on-samsung-tv

I'd like to think that they just forked this project and finished it.
Will you continue with this?

Either way: big thanks, you did an amazing job.

**Comment by ajole13** [comment]
The truth for advertising would love to continue this app for Samsung but I know it's a lot of work to keep this online. Anyway while it works I prefer this app than the official. Thank you for all the work and effort of all of you.

**Comment by heymrlen** [comment]
Hopefully there's support for older Samsung TV model since the official app is only for newer tizen models.
