### ISSUE TITLE
Force next Episode on Countdown Click

### ISSUE THREAD

**Issue by CollinHerber** [jhassan8/crunchyroll-tizen#19]
First of all, I can't thank you enough for this. It is an absolute tragedy that crunchyroll is so hesitant to add native TV apps for non-android experiences. I've got some suggestions/bugs to report and wanted to post them here. I may end up contributing the changes myself but that just depends on when time allows.

**Is your feature request related to a problem? Please describe.**
When there is 60 seconds left in an episode there is a counter that appears. I would like to be able to hit the right button on my remote and it goes into a clickable area which allows you to skip to the next episode.

**Describe the solution you'd like**
1. At 60 seconds the countdown appears.
2. I hit the "RIGHT" button on my remote
3. I am brought into a clickable area which is that countdown. 
    * Perhaps new text appears saying "Next Episode"
4, If I click that the next episode is forced.

**Describe alternatives you've considered**
Instead just have a force next episode button in the player itself.

**Additional context**
The main reason for this is when you try to skip 15 seconds ahead when it's got less than a minute remaining it seems to skip back to wherever you tried to skip from. Being able to force next episode somehow would be great.

**Comment by jhassan8** [comment]
hi, is there something similar... when the "next episode" is displayed by pressing the center button (enter), it goes to the next episode. In case you don't want to go to the next episode by pressing return, it cancels the "next episode." Maybe it's not very intuitive :D It could be improved.
