### ISSUE TITLE
Last viewed

### ISSUE THREAD

**Issue by Nexow91** [jhassan8/crunchyroll-tizen#20]
Hello I have said it before but thank you very much for this app and this support for this project. 

I use the app more denje with each update it makes more fun to use the app. 

**Describe the bug**
However, I always find small things that could be fixed. 

What I noticed recently is the category "last viewed" unfortunately this is not updated after what you have seen. 

**To Reproduce**
For example, I finish watching a series, turn off the TV and turn it back on the next day, and the last series I watched is one that is much longer in the past. 

Thanks already and greetings

**Comment by jhassan8** [comment]
It was solved, any problem let me know.
