### ISSUE TITLE
Some Features v1

### ISSUE THREAD

**Issue by Nexow91** [jhassan8/crunchyroll-tizen#21]
Hello,

i have some ideas it would be nice if these could be implemented. 

1. german or language sub / dub filter Possibly with permanently active function.
2. filter / search series by language.  
3. skip intro possibly self-adjustable for each series for those where it does not go automatically.

If this could be integrated it would make the app even more flexible and innovative. 

Greetings and thx for nice work.

**Comment by Nexow91** [comment]
Hey @jhassan8 take a look into my discussions post please :)

**Comment by Nucito** [comment]
skip intro = perfect 😀

**Comment by jhassan8** [comment]
Hi @Nexow91, @Nucito In the latest update [(v1.1)](https://github.com/jhassan8/crunchyroll-tizen/releases/tag/v1.1), the function to **skip the intro** has been added. If you're using the **online version**, it's highly likely that you already have it updated and ready to use. However, if you're using the **offline version**, you need to install the new version. Regards.

**Comment by Nexow91** [comment]
Hello hanks for the update post. Im using the online version. Im like what are u doing. Thx for the .bat to easy install the app. 
Im updating on the newest version and give feedback :) 

My colleagues also noticed what else would be good in the app or what could be added. 

1. next episode button on the top right of the videos would be great so that you can manually switch to the next episode before the end is reached.

2. the next episode is not correctly taken over if you watch on another device is still continued at the last watched on the TV episode.

Of course, I do not know now if you have already fixed or integrated in the latest version. 

Nevertheless, we are thrilled and glad that we have found someone who provides us and the rest of the community with such a great app. 


Greetings Nexow

**Comment by Nexow91** [comment]
> Hi @Nexow91, @Nucito In the latest update [(v1.1)](https://github.com/jhassan8/crunchyroll-tizen/releases/tag/v1.1), the function to **skip the intro** has been added. If you're using the **online version**, it's highly likely that you already have it updated and ready to use. However, if you're using the **offline version**, you need to install the new version. Regards.


Hi @jhassan8 I have now been able to test the Skip Intro feature for some time and it works beautifully. So I thought I give a positive feedback the application is getting better and better I'm already looking forward to more features you create what not even Samsung and streaming providers provide one :)
