### ISSUE TITLE
Episodes list not showing

### ISSUE THREAD

**Issue by ElZombieIsra** [jhassan8/crunchyroll-tizen#22]
**Describe the bug**
When I open the episodes screen, I see a loader briefly. After that, the layout for the episodes shows up, but there's not a single episode listed. This happens in all the shows 

**To Reproduce**
1. Search for a show
2. Enter its detail page
3. Click on the "Episodes" tab
4. See the error

**Expected behavior**
A list of the show episodes shows up

**Screenshots**
![image](https://github.com/jhassan8/crunchyroll-tizen/assets/17725111/0c709a2e-d3e4-4b48-8b07-29a5f1265f24)

**TV (please complete the following information):**
 - Model: UN55TU7000FXZX
 - Software version: T-KTSU2AKUC-2401.0

**Additional context**

**Comment by jhassan8** [comment]
It was solved, any problem let me know.

**Comment by jhassan8** [comment]
hi @EnDavino, could you tell me what anime you are trying to watch and if you selected it from the **home list, home continue watching, history, browse or search** to find the cause and fix it
