### ISSUE TITLE
Cannot load app

### ISSUE THREAD

**Issue by eduromanc** [jhassan8/crunchyroll-tizen#45]
I installed a few months ago, the app work perfectly to 2 days ago, but now not load. I had think that maybe are any problem of Crunchyroll, but I check on Chromecast and it work.

I open the app, but this stay on load .....
I awaiting for more that one hours.
![20230829_212658](https://github.com/jhassan8/crunchyroll-tizen/assets/69904374/7774c794-e2e7-4354-93ac-d87a50fcafcf)

Step to get error 
1. Turn on tv
2. Open app
3. Stay on load for ever.

I restart the tv (press more that five seconds power button) same error.
I have last version of app 

Tv info
Código del modelo: UNSORU7400GXZS
-Número de serie: 08DV3CXM900....
-ID del dispositivo TVkey: 000000020921d4....
Versión de software: T-MSLUABC-1401.0, BT-S
- Código de estado: 10201 AA4AC17_KA17
-Versión Sub-micom: T-MLINTV-1008

When try see app information (go to app press enter button ) give this error
![20230829_214345](https://github.com/jhassan8/crunchyroll-tizen/assets/69904374/507543a2-89bf-4448-ab7c-f11297789bc7)

Cannot reinstall I have error (with tv option menu -> reinstall)

**Comment by ezequielantunez** [comment]
In my case since 5 minutes ago the app request for login but it doesn't.
Trying to update the app also show the message in the issue screen shot about maintenance

**Comment by ezequielantunez** [comment]
> In my case since 5 minutes ago the app request for login but it doesn't. Trying to update the app also show the message in the issue screen shot about maintenance
> 
> The official android app is working.

Now the app is working from my side.

**Comment by jhassan8** [comment]
@ezequielantunez great that it works, it seems that it was Samsung maintenance.

@eduromanc do you still have the loading problem?
write to me at jhassan8@outlook.com I'll give you some credentials to verify that it's not a problem with content of the account 

regards

**Comment by jhassan8** [comment]
@eduromanc error solved, any other error you have let us know, regards

**Comment by jhassan8** [comment]
@eduromanc error solved, any other error let me know, regards

**Comment by eduromanc** [comment]
Thanks @jhassan8  the issue had been fixed.
