### ISSUE TITLE
German or other another language series can not be played.

### ISSUE THREAD

**Issue by Nexow91** [jhassan8/crunchyroll-tizen#5]
Hi I have tested the app yesterday briefly and could determine that some series could not be played. Mainly German or French albums can not be played, English or original series could be played. Maybe there is a conflict because the series with their respective language are packed in subfolders but this is just a pure guess. 

Not playable means in the case it comes to a loading screen or the jump to the consequence but after that a black screen occurs and this remains even after several minutes waiting. The episodes that can be played also go normally in the jump to the episode, but these can be played. 

I hope I could help.

**Comment by jhassan8** [comment]
the error is in the crunchyroll api, only the vod sub, and dub eng work... I'm going to try to migrate from the api to the new version that uses the new crunchyroll page,
Maybe it will take a few days.

**Comment by Nexow91** [comment]
okay thx for your help :)
