### ISSUE TITLE
bugged home screen

### ISSUE THREAD

**Issue by VirusLabIT** [jhassan8/crunchyroll-tizen#52]
in my samsung monitor m7 32" the home screen is bugged look picture

![20230924_121611 1](https://github.com/jhassan8/crunchyroll-tizen/assets/145903078/c8ce21c7-7746-4570-9fd3-d88002629e13)

**Comment by Clauberto** [comment]
the same thing is happening to me too

**Comment by jhassan8** [comment]
hi @VirusLabIT, please test the new my list screen (v1.1.5) with more than one crunchylist, to check if the solution implemented there works, so I replicate it on the other screens...

if you have the ..._online.wgt version installed, it is not necessary to reinstall the app, just turn off the TV and turn it on again to clean the app cache and load the new one version.

if you have the ..._offline_vX.X.X.wgt version installed, you must install the new version.

thanks

**Comment by Clauberto** [comment]
On my 32" TV it looks like this.


https://github.com/jhassan8/crunchyroll-tizen/assets/68787027/2c293453-f286-4adb-9fea-2d9d96ef9b03


I believe there is a lot of spacing between items.

**Comment by VirusLabIT** [comment]
It fixed thanks
