### ISSUE TITLE
Settings on app not updating / not being correctly pulled

### ISSUE THREAD

**Issue by BSPiotr** [jhassan8/crunchyroll-tizen#62]
**Describe the bug**
The new settings menu is not correctly updating settings - for this specific example:
Subtitles were set to English on crunchyroll website
Before this recent update, Playing a Japanese anime correctly ran the English subtitles
After this update, Playing a show defaults to "no subtitles"
The option in the settings menu is set to "english" already.
Changing the option to "spanish" to check and see if it a null pointer does not have any difference in default subtitle (on a show that has spanish as an option; i.e. it is still default to "no subtitle").
The option menu STILL will show english as a default subtitle when going back to check if it stuck, but the crunchyroll website now shows Spanish as the updated preference.
Moving from one episode to the next changes the default subtitle back to "no subtitle" (Arguably the worst part of the bug)

**To Reproduce**
1. Go to 'options'
2. Select Subtitles
3. Click on Known leanguage
4. Check an episode that has known language option
5. See error when checking the episode (as it is by default off, and goes back to off when changing episodes)

**Expected behavior**
Changes to stick between episodes

**Comment by jhassan8** [comment]
Hi @BSPiotr, resolved in version 1.1.3a.

If you are using the 'online' wgt, it will update when you restart the TV, can check in Settings -> About
you should have version 1.1.3a. It should also notify you that it has been updated when you start the app.

If you are using a .wgt with a version number, you should download the zip file again from the 1.1.3 release.

**Comment by BSPiotr** [comment]
Thank you, it appears to be working now :)
