### ISSUE TITLE
Audio / Subtitles changes after a episode / new Series

### ISSUE THREAD

**Issue by Nexow91** [jhassan8/crunchyroll-tizen#66]
**Describe the bug**

Hi, I've noticed that after the latest update, if you set the audio to German, for example, after each episode the audio language changes to English or another language, sometimes the subtitles also change. This means that every time the audio language has to be reset to the desired language, regardless of whether I start a new series or the next episode.

**Screenshots**
![20231122_144739.jpg](https://github.com/jhassan8/crunchyroll-tizen/assets/73191540/7ee10e84-200d-436b-83fb-267adf41a000)

![20231122_144752.jpg](https://github.com/jhassan8/crunchyroll-tizen/assets/73191540/e4c4c49c-bd2b-4b9e-9c71-25a920325efb)

![20231122_144711.jpg](https://github.com/jhassan8/crunchyroll-tizen/assets/73191540/45731d83-2cb0-482b-a654-9e4b82185cdc)

![20231122_145553.jpg](https://github.com/jhassan8/crunchyroll-tizen/assets/73191540/1ea2d6af-0ec6-4878-a7bd-ce25cd14c7de)

TV Model: 85" Neo QLED 8K QN900A

**Additional context**
Thx for your great work and for this update 😊

**Comment by soerenOsisa** [comment]
I've noticed the same behaviour, but I found a workaround for it by choosing the right season (eg some anime (german) - if I intend on keeping it in that language, it stays between episodes)
