### ISSUE TITLE
I can't log in anymore

### ISSUE THREAD

**Issue by Clauberto** [jhassan8/crunchyroll-tizen#79]
I can no longer log in after the last update, I don't know if it was a TV update or an application update.

TV model: UN32T4300

Every time I try to log in it quickly gives me a loading screen and then suddenly goes back to the login screen.

**Comment by jhassan8** [comment]
Hi @Clauberto, It was already reported and resolved in [https://github.com/jhassan8/crunchyroll-tizen/issues/77](https://github.com/jhassan8/crunchyroll-tizen/issues/77)

If you continue with the error, let me know, regards
