### ISSUE TITLE
Need help with installation

### ISSUE THREAD

**Issue by AdaiasMagdiel** [jhassan8/crunchyroll-tizen#8]
Hi guys, I'm new to all of this, it's my first time installing apps from outside sources and I don't know how to do it. I've already downloaded Tizen Studio and the necessary tools, but I don't understand what to do now. Can anyone help me?

**Comment by jhassan8** [comment]
Hi, I added some instructions to install it in the README, let me know if it helped you.

**Comment by AdaiasMagdiel** [comment]
I'm very grateful, I finally managed to install, thank you very much for the help.
