### ISSUE TITLE
Launch of the Crunchyroll app on LG Web OS

### ISSUE THREAD

**Issue by Nicolucaspro** [jhassan8/crunchyroll-tizen#83]
Actual situation
Currently, LG users have been left without access to Crunchyroll because it has not yet been possible to update the old application that existed before since it has a login error. 

Question from the community 
We would like to know how soon a new version for the operating system could be presented by the creator of this application for Tizen. 

Alternatives
From reusing the old version in which we were already working and updating it either with a new interface or other things such as working as they probably do in a new version that allows us to log in again.

**Comment by jhassan8** [comment]
hi @Nicolucaspro, it is possible, I was currently returning to this, I just don't have an LG TV to do the tests, it works correctly in the emulator.  We were discussing the topic in the following discussion [https://github.com/jhassan8/crunchyroll-tizen/discussions/73](https://github.com/jhassan8/crunchyroll-tizen/discussions/73)

**Comment by Nicolucaspro** [comment]
> hi @Nicolucaspro, it is possible, I was currently returning to this, I just don't have an LG TV to do the tests, it works correctly in the emulator. We were discussing the topic in the following discussion #73

I have an LG television and it could be used to test the project since I want to help beforehand so that it is public and we have a platform to watch Crunchyroll
