### ISSUE TITLE
I didn't have any problem, it was just that I hadn't paid the monthly payment on my account, sorry.











### ISSUE THREAD

**Issue by Sebas825** [jhassan8/crunchyroll-tizen#89]
but I liked the previous selection bar better, it looked more minimalist

**Comment by jhassan8** [comment]
hi @Sebas825, will you have a screenshot or in which episode it happens and what anime, language or type of account?  To try to replicate the error.

**Comment by Sebas825** [comment]
in all episodes the anime is called shigatsu wa kimi no use

https://github.com/jhassan8/crunchyroll-tizen/assets/157090360/b0ece90b-503e-4ce8-b729-dfb8e1ca024b




https://github.com/jhassan8/crunchyroll-tizen/assets/157090360/07312625-e322-48f3-b999-85203759435c

it's not in the right episode
