### ISSUE TITLE
Crunchyroll tizen keeps loading forever

### ISSUE THREAD

**Issue by lucasgrizante** [jhassan8/crunchyroll-tizen#97]
First of all, thank you for providing this awesome app!

Regarding the bug:
**Describe the bug**
Sometimes (not 100% reproducible), when I turn off the TV while the app is open, and some time after I try to turn the TV on again, the app is loaded in the screen, but it keeps loading forever (the white logo screen). I can go to the home and switch to other apps, but when I try to open the crunchyroll tizen app, it still keeps loading forever. The only way to recover is doing a logout and login again (which is not good, because we have to use the TV controller to type the email / password) 

My TV is Samsung qn90b, and I'm using the latest version of the app (1.15 I guess)

**Comment by jhassan8** [comment]
hi @lucasgrizante, The truth is, I had never tried the app open without use for a long time, I am going to review and look for the problem to solve it, thank you
